package com.ywq.ti.entity;

import java.util.Date;

public class AppMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Date create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_message.is_read
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Integer isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.id
     *
     * @return the value of app_message.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.id
     *
     * @param id the value for app_message.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.user_id
     *
     * @return the value of app_message.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.user_id
     *
     * @param userId the value for app_message.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.msg
     *
     * @return the value of app_message.msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.msg
     *
     * @param msg the value for app_message.msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.create
     *
     * @return the value of app_message.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Date getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.create
     *
     * @param create the value for app_message.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setCreate(Date create) {
        this.create = create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_message.is_read
     *
     * @return the value of app_message.is_read
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_message.is_read
     *
     * @param isRead the value for app_message.is_read
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }
}