package com.ywq.ti.entity;

public class AppUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.union_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.mobile_number
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.nick_name
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.level
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.union_id
     *
     * @return the value of app_user.union_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.union_id
     *
     * @param unionId the value for app_user.union_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.mobile_number
     *
     * @return the value of app_user.mobile_number
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.mobile_number
     *
     * @param mobileNumber the value for app_user.mobile_number
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.nick_name
     *
     * @return the value of app_user.nick_name
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.nick_name
     *
     * @param nickName the value for app_user.nick_name
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.level
     *
     * @return the value of app_user.level
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.level
     *
     * @param level the value for app_user.level
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}