package com.ywq.ti.entity;

import java.util.Date;

public class AppUserBonus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_bonus.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_bonus.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_bonus.event_msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String eventMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_bonus.bonus
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Integer bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_bonus.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Date create;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_bonus.id
     *
     * @return the value of app_user_bonus.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_bonus.id
     *
     * @param id the value for app_user_bonus.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_bonus.user_id
     *
     * @return the value of app_user_bonus.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_bonus.user_id
     *
     * @param userId the value for app_user_bonus.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_bonus.event_msg
     *
     * @return the value of app_user_bonus.event_msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getEventMsg() {
        return eventMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_bonus.event_msg
     *
     * @param eventMsg the value for app_user_bonus.event_msg
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setEventMsg(String eventMsg) {
        this.eventMsg = eventMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_bonus.bonus
     *
     * @return the value of app_user_bonus.bonus
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_bonus.bonus
     *
     * @param bonus the value for app_user_bonus.bonus
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_bonus.create
     *
     * @return the value of app_user_bonus.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Date getCreate() {
        return create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_bonus.create
     *
     * @param create the value for app_user_bonus.create
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setCreate(Date create) {
        this.create = create;
    }
}