package com.ywq.ti.entity;

public class AppUserSubscribe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_subscribe.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_subscribe.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_subscribe.address
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_subscribe.topic
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String topic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_subscribe.id
     *
     * @return the value of app_user_subscribe.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_subscribe.id
     *
     * @param id the value for app_user_subscribe.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_subscribe.user_id
     *
     * @return the value of app_user_subscribe.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_subscribe.user_id
     *
     * @param userId the value for app_user_subscribe.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_subscribe.address
     *
     * @return the value of app_user_subscribe.address
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_subscribe.address
     *
     * @param address the value for app_user_subscribe.address
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_subscribe.topic
     *
     * @return the value of app_user_subscribe.topic
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_subscribe.topic
     *
     * @param topic the value for app_user_subscribe.topic
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }
}