package com.ywq.ti.entity;

public class AppWalletTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_wallet_tag.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_wallet_tag.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_wallet_tag.wallet
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String wallet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_wallet_tag.tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_wallet_tag.id
     *
     * @return the value of app_wallet_tag.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_wallet_tag.id
     *
     * @param id the value for app_wallet_tag.id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_wallet_tag.user_id
     *
     * @return the value of app_wallet_tag.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_wallet_tag.user_id
     *
     * @param userId the value for app_wallet_tag.user_id
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_wallet_tag.wallet
     *
     * @return the value of app_wallet_tag.wallet
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getWallet() {
        return wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_wallet_tag.wallet
     *
     * @param wallet the value for app_wallet_tag.wallet
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setWallet(String wallet) {
        this.wallet = wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_wallet_tag.tag
     *
     * @return the value of app_wallet_tag.tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_wallet_tag.tag
     *
     * @param tag the value for app_wallet_tag.tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}