package com.ywq.ti.entity;

import java.util.Date;

public class BcErc20Transaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.tx_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String tokenAddress; 

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.block_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String blockHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.block_number
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.gas
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long gas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.gas_price
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long gasPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.send_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String sendAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.receive_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String receiveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.value
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_transaction.timestamp
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.tx_hash
     *
     * @return the value of bc_erc20_transaction.tx_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.tx_hash
     *
     * @param txHash the value for bc_erc20_transaction.tx_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.token_address
     *
     * @return the value of bc_erc20_transaction.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getTokenAddress() {
        return tokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.token_address
     *
     * @param tokenAddress the value for bc_erc20_transaction.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTokenAddress(String tokenAddress) {
        this.tokenAddress = tokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.block_hash
     *
     * @return the value of bc_erc20_transaction.block_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getBlockHash() {
        return blockHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.block_hash
     *
     * @param blockHash the value for bc_erc20_transaction.block_hash
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setBlockHash(String blockHash) {
        this.blockHash = blockHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.block_number
     *
     * @return the value of bc_erc20_transaction.block_number
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getBlockNumber() {
        return blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.block_number
     *
     * @param blockNumber the value for bc_erc20_transaction.block_number
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setBlockNumber(Long blockNumber) {
        this.blockNumber = blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.gas
     *
     * @return the value of bc_erc20_transaction.gas
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getGas() {
        return gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.gas
     *
     * @param gas the value for bc_erc20_transaction.gas
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setGas(Long gas) {
        this.gas = gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.gas_price
     *
     * @return the value of bc_erc20_transaction.gas_price
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getGasPrice() {
        return gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.gas_price
     *
     * @param gasPrice the value for bc_erc20_transaction.gas_price
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setGasPrice(Long gasPrice) {
        this.gasPrice = gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.send_address
     *
     * @return the value of bc_erc20_transaction.send_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.send_address
     *
     * @param sendAddress the value for bc_erc20_transaction.send_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.receive_address
     *
     * @return the value of bc_erc20_transaction.receive_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.receive_address
     *
     * @param receiveAddress the value for bc_erc20_transaction.receive_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.value
     *
     * @return the value of bc_erc20_transaction.value
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.value
     *
     * @param value the value for bc_erc20_transaction.value
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setValue(Long value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_transaction.timestamp
     *
     * @return the value of bc_erc20_transaction.timestamp
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_transaction.timestamp
     *
     * @param timestamp the value for bc_erc20_transaction.timestamp
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}