package com.ywq.ti.entity;

public class BcErc20Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String tokenAddress; //长度 42

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.token_name
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String tokenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.symbol
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.total_supply
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long totalSupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.decimals
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.holders
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long holders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bc_erc20_token.transfers
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    private Long transfers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.token_address
     *
     * @return the value of bc_erc20_token.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getTokenAddress() {
        return tokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.token_address
     *
     * @param tokenAddress the value for bc_erc20_token.token_address
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTokenAddress(String tokenAddress) {
        this.tokenAddress = tokenAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.token_name
     *
     * @return the value of bc_erc20_token.token_name
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getTokenName() {
        return tokenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.token_name
     *
     * @param tokenName the value for bc_erc20_token.token_name
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTokenName(String tokenName) {
        this.tokenName = tokenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.symbol
     *
     * @return the value of bc_erc20_token.symbol
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.symbol
     *
     * @param symbol the value for bc_erc20_token.symbol
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.total_supply
     *
     * @return the value of bc_erc20_token.total_supply
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getTotalSupply() {
        return totalSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.total_supply
     *
     * @param totalSupply the value for bc_erc20_token.total_supply
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTotalSupply(Long totalSupply) {
        this.totalSupply = totalSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.decimals
     *
     * @return the value of bc_erc20_token.decimals
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.decimals
     *
     * @param decimals the value for bc_erc20_token.decimals
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setDecimals(Long decimals) {
        this.decimals = decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.holders
     *
     * @return the value of bc_erc20_token.holders
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getHolders() {
        return holders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.holders
     *
     * @param holders the value for bc_erc20_token.holders
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setHolders(Long holders) {
        this.holders = holders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bc_erc20_token.transfers
     *
     * @return the value of bc_erc20_token.transfers
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public Long getTransfers() {
        return transfers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bc_erc20_token.transfers
     *
     * @param transfers the value for bc_erc20_token.transfers
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    public void setTransfers(Long transfers) {
        this.transfers = transfers;
    }
}