package com.ywq.ti.dao;

import com.ywq.ti.entity.AppMessage;

public interface AppMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insert(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insertSelective(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    AppMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKeySelective(AppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKey(AppMessage record);
}