package com.ywq.ti.dao;

import com.ywq.ti.entity.AppUserSubscribe;

public interface AppUserSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insert(AppUserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insertSelective(AppUserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    AppUserSubscribe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKeySelective(AppUserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_subscribe
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKey(AppUserSubscribe record);
}