package com.ywq.ti.dao;

import com.ywq.ti.entity.AppWalletTag;

public interface AppWalletTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insert(AppWalletTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int insertSelective(AppWalletTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    AppWalletTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKeySelective(AppWalletTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_wallet_tag
     *
     * @mbg.generated Mon Jun 25 18:22:27 CST 2018
     */
    int updateByPrimaryKey(AppWalletTag record);
}