package com.ywq.ti.dao;

import com.ywq.ti.entity.BcErc20Transaction;

public interface BcErc20TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int deleteByPrimaryKey(String txHash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insert(BcErc20Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insertSelective(BcErc20Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    BcErc20Transaction selectByPrimaryKey(String txHash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKeySelective(BcErc20Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKey(BcErc20Transaction record);
}