package com.ywq.ti.dao;

import com.ywq.ti.entity.BcErc20Token;

public interface BcErc20TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int deleteByPrimaryKey(String tokenAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insert(BcErc20Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insertSelective(BcErc20Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    BcErc20Token selectByPrimaryKey(String tokenAddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKeySelective(BcErc20Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_erc20_token
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKey(BcErc20Token record);
}