package com.ywq.ti.dao;

import com.ywq.ti.entity.BcTransaction;

public interface BcTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int deleteByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insert(BcTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int insertSelective(BcTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    BcTransaction selectByPrimaryKey(String hash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKeySelective(BcTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bc_transaction
     *
     * @mbg.generated Wed May 23 10:12:10 CST 2018
     */
    int updateByPrimaryKey(BcTransaction record);
}